### ISSUE TITLE
Packagist setup

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataClassificationMediaBundle#2]
We need a packagist setup for this repository to use the dev-kit. Refs https://github.com/sonata-project/dev-kit/pull/193

**Comment by rande** [comment]
done!

**Comment by rande** [comment]
https://packagist.org/packages/sonata-project/classification-media-bundle

**Comment by greg0ire** [comment]
Thanks @rande !

**Comment by core23** [comment]
Yeah! 🎉 🎈 🎊
